### ISSUE TITLE
What is the meaning of BTO's 'related to'?

### ISSUE THREAD

**Issue by matentzn** [BRENDA-Enzymes/BTO#7]
You have about 80 assertions like:

```
[Term]
id: BTO:0001201
name: rosette
namespace: BrendaTissueOBO
def: ".." [...]
relationship: related_to BTO:0000713 ! leaf
```

What is the intention to use a very general relation such as 'related to' here? What does this mean? What is it used for?

**Comment by BRENDA-Enzymes** [comment]
Will have to check with Marion and get back to you as soon as possible.

**Comment by BRENDA-Enzymes** [comment]
In the newest version most of theses relationships are already replaced by more meaningful relations.

**Comment by matentzn** [comment]
This is great thanks!

**Comment by BRENDA-Enzymes** [comment]
all "related_to" relationships replaced in v2020-04-23
