### ISSUE TITLE
'endothelial cell' has incorrect part_of link to heart

### ISSUE THREAD

**Issue by dosumis** [BRENDA-Enzymes/BTO#9]
BTO asserts that all endothelial cells are part of the heart, leading to problems like this:

![image](https://user-images.githubusercontent.com/112839/75267206-daec3400-57ed-11ea-95a0-f03d80e23c6c.png)

=> part_of the liver is part_of the heart

**Comment by BRENDA-Enzymes** [comment]
Fixed in release 2020.2
